# .github/workflows/treebeard.yml
# Run all notebooks on every push and daily
on:
  push:
  schedule:
    - cron: "0 12 * * *" # daily at 12:00
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@master