# .github/workflows/treebeard.yml
# Run all notebooks on every push and daily
on:
  push:
  schedule:
    - cron: "0 10,22 * * *" # twice daily
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "DunnCounty_COVID19.ipynb"
        params: "params.json"
        isReport: True
        poll: False
    - name: move notebook
      run: |
        cp /home/runner/work/_temp/nb-runner/DunnCounty_COVID19.ipynb .
    - name: Commit and push files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add DunnCounty_COVID19.ipynb
        git commit -m "Update notebook" -a
        git push origin master
